version = 3.11.1
runner.dialect = scala3
maxColumn = 140
indent.main = 4
indent.callSite = 4
indent.commaSiteRelativeToExtends = 4
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
rewrite.trailingCommas.style = always
docstrings.wrap = keep
project.git = true
lineEndings = unix
